[network] Fix incorrect usage of select_next_some in onchain discovery
`stream.select_next_some()` returns a `FusedFuture`, which expects
callers to check `is_terminated` before polling to ensure callers don't
poll the future after it's completed.

In this case, `simple-onchain-discovery` was incorrectly using
`select_next_some` inside a loop, expecting that the `reconfig_events`
channel would never close. However, it appears that we get occasional
panics during node shutdown, as referenced by this comment in diem-node:

> Shutdown network runtimes to avoid panic error log after DiemHandle is dropped:
> thread ‘network-’ panicked at ‘SelectNextSome polled after terminated’,...
> stack backtrace:
>    ......
>    8: network_simple_onchain_discovery::ConfigurationChangeListener::start::{{closure}}
>      at network/simple-onchain-discovery/src/lib.rs:175
>    ......
> Other runtimes don't have same problem.