Revert "Bump .NET SDK from 5.0 to 6.0"
This reverts commit 81c37b3949ecbac7beda268e254ac57c0ddd0696 since CI
was picking up test failures when running the move-prover test suite:

```
test prover unit[simplify]::functional/unused_schema.move ... FAILED
Error: cannot extract version from `/opt/dotnet/tools/boogie`
```

Closes: #9995